import type { Metadata } from 'next'
import ClerkProvider from '@/providers/ClerkProvider'
import MUIProvider from '@/providers/MUIProvider'

export const metadata: Metadata = {
  title: 'Mystict Boilerplate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <MUIProvider>
          <body>{children}</body>
        </MUIProvider>
      </html>
    </ClerkProvider>
  )
}
